# Generated by Django 5.1.1 on 2024-10-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
