# Generated by Django 5.1.1 on 2024-10-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_task_has_sub_tasks_subtask_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='task_set',
            field=models.ManyToManyField(blank=True, related_name='task_list', to='api.task'),
        ),
    ]
